# -*- coding: utf-8 -*-
"""Lab02_ZeynepEslem_GÖKÇE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MoDH6lWiMCuLuEUUdHy_Qtr3Rm4vjZO9

# DSA 107 — Lab 2: Summarising one variable, then two

**Week 2 · w/c 5 October 2026** · paired with DSA 101 lecture week 2

**Name:** Zeynep Eslem GÖKÇE  **Student ID:** 26022121013

---

### What you will produce

A runnable Colab notebook, pushed to your `dsa107-labs` repository. In it you summarise one categorical variable, count two categorical variables together, turn those counts into rates, summarise one quantitative variable, and draw three labelled figures.

### Before you start

Run the setup cell below. If any import fails, run
`!pip install pandas matplotlib seaborn` in a new cell and try again.

### How to use this notebook

Every code cell has a **Goal** written just above it. Read the goal, then write the code. You do not need to open the handout while you work — everything you have to do is in this notebook.

The **Command reference** below holds the commands you need for this lab, and a few more besides. Read it once now, and come back to it whenever you are stuck.
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", 50)
sns.set_theme(style="whitegrid")
print("pandas", pd.__version__)

"""## 1. Load the data and look at it

`pd.read_csv` accepts a URL just as happily as a filename.

This is a Titanic passenger list, but **it is not the same file used in the lecture**. Your numbers will not match your lecture notes, and they are not supposed to. The method is what carries over, not the answers.

> **Goal 1a.** Load the CSV into a DataFrame called `titanic`, then show its first five rows.
"""

titanic = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv")

# TODO: show the first five rows

titanic.head(5)

"""> **Goal 1b.** Print the shape of the table, then print the column names, their types and their non-missing counts."""

# TODO: print the shape, then call .info()

print(titanic.shape)
print(titanic.info())

"""> **Goal 1c.** Count the missing values in each column, and show the worst column first."""

# TODO: count the missing values per column, sorted from most to fewest
titanic_missing = titanic.isna().sum()
titanic_missing.sort_values(ascending=False)

"""**Q1.** How many rows and how many columns are there, and what does one row represent?
Which column has the most missing values, roughly what fraction of the rows is that, and would you use that column in an analysis?

**A1.** There are 891 rows and 15 columns. A row represents the data of 15 columns according to one person.

## 2. One categorical variable

A **categorical** variable puts each row into a group: `sex`, `embarked`, `pclass`.
A **quantitative** variable measures an amount: `age`, `fare`.

Be careful: `pclass` is stored as the numbers 1, 2 and 3, but it is still categorical. The number 2 is a label, not an amount — second class is not "twice" first class. How a variable is *stored* and what kind of variable it *is* are two different questions.

For a categorical variable the summary is a count of every category. That table of counts has a name: the **distribution** of the variable.

> **Goal 2a.** Count how many passengers were in each class. Sort the result by class number, not by count, and store it in a variable called `counts_class` so you can draw it later.
"""

# TODO: counts of each passenger class, in class order, stored as counts_class
df = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv")
print(df["class"].value_counts().sort_index())
counts_class = df["class"].value_counts().sort_index()

"""> **Goal 2b.** Show the same summary as proportions instead of counts, and check that they add up to 1."""

# TODO: the same table as proportions, plus a check that they sum to 1
#df = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv")

x = (df["class"].value_counts(normalize=True))

print(x.sum())
(df["class"].value_counts(normalize=True))

"""> **Goal 2c.** Draw a bar chart of the class counts. Give it an x label, a y label and a title."""

# TODO: labelled bar chart of the class counts
df["class"].value_counts().sort_index().plot.bar()
plt.title("Class Counts")
x1 = ["class"]
y1 = ["number"]
plt.xlabel("class")
plt.ylabel("number")
plt.show()

"""**Q2.** What fraction of the passengers travelled in third class?
If you picked one passenger from this dataset at random, what is the probability that they were in first class?
Write one sentence explaining why a proportion and a probability are the same number here.

**A2.** %55.11 of the passengers were third class.
The probability of a random passenger being first class is %24.24.
 Proportion and probability are the same because the only difference they have is while proportion is out of 1, prbability is out of 100.

## 3. Two variables, and the denominator question

One variable on its own cannot answer "did class affect survival". You need the pair.

`pd.crosstab` counts every combination of two variables. The first argument runs down the side of the table, the second runs across the top.

Then comes the hard idea of the week. **The same six numbers become different tables depending on what you divide by, and the denominator is the question you are asking.**

| Table | Divide every cell by | The question it answers |
| --- | --- | --- |
| Joint | the grand total | P(third class **and** died) |
| Marginal | nothing — just add up | P(third class) |
| Conditional | its own row total | P(died **given** third class) |

Only the conditional table compares groups of different sizes fairly, because every row adds up to 1 whatever the size of the group.

> **Goal 3a.** Make a crosstab with `pclass` down the side and `survived` across the top. Store it in a variable called `counts` and print it.
"""

# TODO: build the crosstab and print it
pclass = titanic['pclass']
survived = titanic['survived']
counts = pd.crosstab(pclass, survived)
pd.crosstab(pclass, survived)

"""> **Goal 3b.** Add up each row of `counts` to get the number of passengers in each class — the marginal counts. Check that they add up to the number of rows in the dataset."""

# TODO: row totals, and a check against len(titanic)

y = counts.sum(axis="columns")
#counts.sum(axis="index")
print(y.sum())
counts.sum(axis="columns")

"""> **Goal 3c.** Build the conditional distribution: every cell divided by its own row total. Store it as `rates`, print it rounded to 3 decimal places, and check that every row adds up to 1."""

# TODO: the conditional distribution, rounded to 3 places, plus a row check

pclass_marginal = counts.sum(axis="columns")
rates = counts.divide(pclass_marginal, axis="rows")
counts.divide(pclass_marginal, axis="rows")

"""> **Goal 3d.** Draw a bar chart of `rates`, with one group of bars per class. Label both axes, the legend and the title."""

# TODO: labelled bar chart of the conditional rates

(rates.divide(pclass_marginal, axis="rows").
 plot.bar(stacked=True))
plt.xlabel("P Class")
plt.ylabel("Diviation")
plt.title("Survial Rate Among P Classes")
plt.show()

"""**Q3.** Which single cell of `counts` holds the largest number, and what does that cell mean? Does that number on its own show that this was the most dangerous class to travel in?

Now look at `rates`. Given that a passenger travelled in third class, what fraction survived, and how does that compare with first class?

In one sentence: which of the two tables answers "did class affect survival", and why?

**A3.** The "pclass 3" cell of counts hold the largest number and it means that there were 491 passengers in that pclass. We can understand it's the most dangerous since 372 of the people of pclass 3 hasn't survived.

The %24.2363 of the pclass 3 passengers have survived, Comparing it to the pclass 1 ,which is %62.963, we can say pclass 1 was safer to be in.

The "rates" table gives us a clearer answer on class affecting survival since we have percentages instead of numbers.

## 4. One quantitative variable

`value_counts` is a poor tool for `age`. There are 88 different ages in this dataset, so the table would be 88 rows long, and each row would carry very little information on its own. You cannot see a shape in a table like that.

So instead we cut the range of ages into **bins**, and count how many values fall into each bin. That is a histogram.

The number of bins is a choice you make. Too few bins hide real structure. Too many bins show noise as if it were structure. There is no correct number — only a number you can defend.

> **Goal 4a.** Draw a histogram of `age` with 10 bins. Label both axes and give it a title that says how many bins you used. Then try one other bin count and keep whichever you prefer.
"""

# TODO: labelled histogram of age
df_CO = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv")

df_CO["age"] = pd.cut(
    df_CO["age"],
    bins=[0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100],
    labels=["0-9", "10-19", "20-29", "30-39", "40-49", "50-59", "60-69", "70-79", "80-85", "86-88"],
    right=False)
df_CO["age"].value_counts(sort=False).plot.bar()
plt.xlabel("Ages")
plt.ylabel("How Many People")
plt.title("Age Distribution using 10 Bins")
plt.show()

"""> **Goal 4b.** Print the mean, the median and the standard deviation of `age`. Then print the mean, the median and the largest value of `fare`. Round everything to 2 decimal places."""

# TODO: centre and spread for age, then centre and largest value for fare
age = titanic['age']
fare = titanic['fare']
print(age.mean())
print(age.median())
print(age.std())
print(fare.mean())
print(fare.median())
print(fare.max())
print(round(29.69911764705882, 2))
print(round(28.0, 2))
print(round(14.526497332334044, 2))
print(round(32.204207968574636, 2))
print(round(14.4542, 2))
print(round(512.3292, 2))
print(round(29.7, 2))

"""**Q4.** Looking at your age histogram, roughly where is the biggest group of passengers?

For `fare`, the mean and the median are far apart. Which one is the honest summary of a typical fare, and what does the size of the gap tell you about the shape of the data?

**A4.** Around 20-29.

The median would be the typical fare since its the median, but the max, min and median value being this far apart shows us the difference between the class types values.

## 5. Push to GitHub

1. You created a repository named `dsa107-labs` in Lab 1. Use the same one.
2. In Colab: **File → Save a copy in GitHub**, and choose that repository.
3. Paste the resulting link in the line below.

**Repository link:** _______________

---

## Submission checklist

- [x ] Every cell runs top to bottom without error (Runtime → Restart and run all)
- [x ] All three figures have an x label, a y label and a title
- [x ] All four written answers are filled in — a figure with no reading of it scores zero on interpretation
- [ x] Notebook saved as `Lab02_Firstname_Lastname.ipynb`
- [ x] Report exported as `Lab02_Firstname_Lastname.pdf`
- [ ] If you used an AI assistant, the log is attached as described in the course AI policy

Submit both files through MS Teams.
"""